[phases.setup]
aptPkgs = ["openjdk-21-jdk", "maven"]

[phases.build]
cmds = ["cd API/area && export MAVEN_OPTS=\"-Xmx256m\" && chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd API/area && java -Xmx256m -jar target/*.jar"
